### ISSUE TITLE
ImportError: cannot import name 'SIGPIPE' from 'signal'

### ISSUE THREAD

**Issue by umar98** [s0md3v/uro#20]
D:\uro>uro
Traceback (most recent call last):
  File "C:\Users\umara\AppData\Local\Programs\Python\Python38\Scripts\uro-script.py", line 33, in <module>
    sys.exit(load_entry_point('uro==0.0.2', 'console_scripts', 'uro')())
  File "C:\Users\umara\AppData\Local\Programs\Python\Python38\Scripts\uro-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\umara\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\umara\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\umara\AppData\Local\Programs\Python\Python38\lib\site-packages\uro-0.0.2-py3.8.egg\uro\uro.py", line 4, in <module>
ImportError: cannot import name 'SIGPIPE' from 'signal' (C:\Users\umara\AppData\Local\Programs\Python\Python38\lib\signal.py)

**Comment by s0md3v** [comment]
You are using an older version of uro. This issue has been fixed, update your installation.

**Comment by umar98** [comment]
![image](https://user-images.githubusercontent.com/42386653/159126627-8c73091a-f371-404e-a220-ee0e2543c60c.png)

Issue still exists!

**Comment by s0md3v** [comment]
It should be fix now, please reinstall.
